set(FEEDER_ROOT_DIR $ENV{HOME}/sys/lib/libfeeder-1.1.0 CACHE STRING "")

SET(FEEDER_FOUND TRUE)
set(FEEDER_VERSION 1.1.0)
set(FEEDER_INCLUDE_DIRS ${FEEDER_ROOT_DIR}/include CACHE STRING "")
set(FEEDER_LIBRARY_DIRS ${FEEDER_ROOT_DIR}/lib CACHE STRING "")
set(FEEDER_LIBRARIES feeder CACHE STRING "")

message(STATUS "FEEDER_FOUND: " ${FEEDER_FOUND})
message(STATUS "FEEDER_VERSION: " ${FEEDER_VERSION})
message(STATUS "FEEDER_INCLUDE_DIRS: " ${FEEDER_INCLUDE_DIRS})
message(STATUS "FEEDER_LIBRARY_DIRS: " ${FEEDER_LIBRARY_DIRS})
message(STATUS "FEEDER_LIBRARIES: " ${FEEDER_LIBRARIES})
